### ISSUE TITLE
Security Issue with used library common-beanutils:1.9.3

### ISSUE THREAD

**Issue by Veranicus** [OWASP/www-project-enterprise-security-api#6]
One of your project's dependencies, specifically common-beanutils in it's latest version 1.9.3 has a security bug CWE-502: Deserialization of Untrusted Data.

**Comment by kwwall** [comment]
Yep; we're aware of it from the GitHub security alerts. It's been fixed in the 'develop' branch for about 4 months now. I'm just waiting on a PR to close another open issue before we push a new release (2.2.1.0) up to Maven Central.

BTW, this was fixed via commit https://github.com/ESAPI/esapi-java-legacy/commit/694c97bcc1152b3aa2eaef5c130c05085ab0c7e9#diff-600376dffeb79835ede4a0b285078036 to address GitHub Issue 512.
